# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI Smoke Test

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
    # only for the main repo... not the docs...
    paths:
      - 'src/**.js'
      - 'src/**.mjs'
      - '.github/workflows/node.js.yml'
  workflow_dispatch:


jobs:
  build:
    # https://wiki.ubuntu.com/Releases
    # Ubuntu 22.04.3 LTS
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node 16 almost eol june 2024
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    # updated to v4...
    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    
    # pnpm project stuff:
    - name: Install dependencies
      run: pnpm install
    - name: Smoke Test
      run: pnpm run test # should rename
      
    # - run: npm ci
    # - run: npm run build --if-present
    # - run: npm test
